# Generated by Django 3.1.6 on 2021-03-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerdatas',
            name='Date',
            field=models.CharField(default='hhh', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peerdatas',
            name='TxHash',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='peerdatas',
            name='UpdatedTxHash',
            field=models.CharField(max_length=1000),
        ),
    ]
